version: '3.8'

services:
  app:
    build: .
    environment:
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_USERNAME=${LASTFM_USERNAME}
    container_name: your_lastfm
    volumes:
      - /mnt/portainer/your_lastfm/data:/app/data
    ports:
      - "1533:1533"
    restart: unless-stopped
